/**
 * hdunit (T03) hand-written smoke sample.
 *
 * NOT generated by T02 and NOT a `.test.ts` — it lives outside the rewritten
 * tree on purpose:
 *
 *   - T02's rewrite script rebuilds tests/happy-dom/rewritten/** by mirroring
 *     the vendor tree, so any hand-written test file dropped there would be
 *     deleted on the next `scripts/rewrite-happy-dom-tests.mjs` run (breaking
 *     T02 idempotency and the T11 CI check);
 *   - the `.sample.ts` suffix stops `bun test tests/happy-dom/adapter` from
 *     auto-discovering it, because this sample depends on the globals injected
 *     by the preload and would fail if run without it.
 *
 * This sample proves the adapter wiring end-to-end:
 *
 *   1. `import { vi } from '<adapter>'` resolves (here the sibling
 *      `./index.js`, the same convention T02 uses for adapter imports);
 *   2. the preload (`tests/happy-dom/adapter/preload.ts`) activates the setup
 *      mechanism: global mockModule / resetMockedModules / restoreAllMocks are
 *      installed and `process.env.TZ` is pinned to `Etc/GMT-2` before this file
 *      evaluates.
 *
 * Run with: `bun run compat:hdunit:test`. When the T02 rewritten tree is not
 * merged yet the runner executes this file alone; once it is, this sample runs
 * alongside the rewritten suite. Equivalent manual invocation:
 * `bun test ./tests/happy-dom/adapter/smoke.sample.ts --preload ./tests/happy-dom/adapter/preload.ts`.
 */

import { test, expect } from 'bun:test';
import { vi } from './index.js';

test('adapter vi is usable from the rewritten tree', () => {
	const fn = vi.fn((x: number) => x * 2);
	expect(fn(2)).toBe(4);

	const object = {
		method(): string {
			return 'real';
		}
	};
	const spy = vi.spyOn(object, 'method').mockReturnValue('mocked');
	expect(object.method()).toBe('mocked');

	vi.restoreAllMocks();
	expect(object.method()).toBe('real');
});

test('setup mechanism is active via the preload', () => {
	const g = globalThis as Record<string, unknown>;
	expect(typeof g.mockModule).toBe('function');
	expect(typeof g.resetMockedModules).toBe('function');
	expect(typeof g.restoreAllMocks).toBe('function');
	expect(process.env.TZ).toBe('Etc/GMT-2');
});

test('mockModule / resetMockedModules workflow via preload globals', async () => {
	const g = globalThis as Record<string, unknown>;
	(g.mockModule as (name: string, module: Record<string, unknown>) => void)('https', {
		request: () => 'SMOKE-MOCKED'
	});

	const httpsModule = await import('https');
	expect((httpsModule as Record<string, unknown>).request('url')).toBe('SMOKE-MOCKED');

	(g.resetMockedModules as () => void)();
	expect(() =>
		(httpsModule as Record<string, unknown>).request('not-a-valid-url')
	).toThrow();
});
